### PR TITLE
Fix playwright serialization

### LINKED ISSUE #44: Script always fails with error "Storybook object not found on window. Open your storybook and check the console for errors."
When running my CLI command (regardless of config), the cli always hangs with the following output:

```
$ npm run test:a11y -- --headless false --browser firefox

> form-frontend@0.1.0 test:a11y /Users/karrui/Projects/FormSG/frontend
> axe-storybook "--headless" "false" "--browser" "firefox"

[firefox] accessibility
Error! The suite failed to run
An error was encountered before we started testing stories. Likely this means the browser failed to open.

Error: Storybook object not found on window. Open your storybook and check the console for errors.

0 passing (0ms)
1 failing
0 pending
```

### PR DESCRIPTION
**Pull request by ahuth**
Fixes #44.

Playwright's [page.evaluate](https://playwright.dev/docs/api/class-page/#page-evaluate) can return `undefined` if the function we pass to it returns something that's not JSON serializable.

We're using it here to return Storybook's representation of a story, and some addon's parameters may not be serializable (for example, MSW handlers).

Fortunately, we only need a couple pieces of a story (name, id, etc), and can avoid this by only returning the specific things we need from the browser.

### CODE REVIEW

File: bin/axe-storybook.js [hunk 1]
```diff
@@ -4,11 +4,11 @@
...
   .then(() => {
-    process.on('exit', () => process.exit(0));
+    process.exit(0);
   })
   .catch((error) => {
     if (error) {
       console.log(error);
     }
-    process.on('exit', () => process.exit(1));
+    process.exit(1);
```
Comment (ahuth) [inline bin/axe-storybook.js:13]: Unrelated to the fix, but I noticed that the script was never exiting in this case.
